### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by ThreeDeePrint** [IncomeStreamSurfer/chatgptassistantautoblogger#7]
Hey ,

I am getting the following after watching your youtube? Haven't changed any files other than the API code and the XML's and Txt's

Any recommendation? ( i installed and reinstalled a few times with clean files and its the same )

C:\Users\xxxx\Desktop\AutoBlogger\chatpgtblogger>py testing3.py               
Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\AutoBlogger\chatpgtblogger\testing3.py", line 26, in <module>
    assistant = client.beta.assistants.create(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\resources\beta\assistants\assistants.py", line 108, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 889, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': 'Failed to index file: Unsupported file file-sAB6UDfZY0Uc7554S2y5YIsJ type: text/csv error_code: unhandled_mimetype', 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by gatoguff** [comment]
Same here. Keep me posted if any solutions arise.

And thank you Hamish for all the amazing work!

**Comment by jennuhhfurr** [comment]
I ran into this same exact issue and can't figure it out :(
